import { BOOKING_SERVICE_CATEGORY_ORDER } from '@/lib/booking/groupServicesByCategory';
import { DEMO_BARBER_IDS, DEMO_SERVICE_IDS } from './ids';

const barberRef = (id: string, name: string) => ({
  barber: { id, name, active: true },
});

const ALL_BARBER_REFS = [
  barberRef(DEMO_BARBER_IDS.jamie, 'Jamie Reed'),
  barberRef(DEMO_BARBER_IDS.alex, 'Alex Morgan'),
  barberRef(DEMO_BARBER_IDS.sam, 'Sam Brooks'),
  barberRef(DEMO_BARBER_IDS.marcus, 'Marcus Bell'),
];

function gbp(pounds: number): number {
  return Math.round(pounds * 100);
}

export const demoServicesResponse = {
  services: [
    {
      id: DEMO_SERVICE_IDS.qualityHaircut,
      name: 'Quality haircut',
      description: 'Classic scissor and clipper finish.',
      pricePence: gbp(35),
      durationMinutes: 30,
      bufferMinutes: 5,
      displayOrder: 1,
      category: 'featured',
      isActive: true,
      barberServices: [barberRef(DEMO_BARBER_IDS.jamie, 'Jamie Reed'), barberRef(DEMO_BARBER_IDS.sam, 'Sam Brooks')],
    },
    {
      id: DEMO_SERVICE_IDS.premiumHaircut,
      name: 'Premium haircut',
      description: 'Full consultation, cut and style.',
      pricePence: gbp(45),
      durationMinutes: 45,
      bufferMinutes: 5,
      displayOrder: 2,
      category: 'featured',
      isActive: true,
      barberServices: [barberRef(DEMO_BARBER_IDS.jamie, 'Jamie Reed'), barberRef(DEMO_BARBER_IDS.alex, 'Alex Morgan')],
    },
    {
      id: DEMO_SERVICE_IDS.qualityBeardTrim,
      name: 'Quality beard trim',
      description: 'Shape, line-up and hot towel finish.',
      pricePence: gbp(15),
      durationMinutes: 15,
      bufferMinutes: 5,
      displayOrder: 3,
      category: 'featured',
      isActive: true,
      barberServices: [barberRef(DEMO_BARBER_IDS.alex, 'Alex Morgan'), barberRef(DEMO_BARBER_IDS.marcus, 'Marcus Bell')],
    },
    {
      id: DEMO_SERVICE_IDS.skinFadeWithHaircut,
      name: 'Skin fade with haircut',
      description: 'Precision fade blended into the top.',
      pricePence: gbp(40),
      durationMinutes: 45,
      bufferMinutes: 5,
      displayOrder: 4,
      category: 'featured',
      isActive: true,
      barberServices: [barberRef(DEMO_BARBER_IDS.jamie, 'Jamie Reed'), barberRef(DEMO_BARBER_IDS.alex, 'Alex Morgan')],
    },
    {
      id: DEMO_SERVICE_IDS.clippersOnly,
      name: 'Clippers only',
      description: 'Quick clipper tidy-up.',
      pricePence: gbp(15),
      durationMinutes: 15,
      bufferMinutes: 5,
      displayOrder: 5,
      category: 'featured',
      isActive: true,
      barberServices: [barberRef(DEMO_BARBER_IDS.sam, 'Sam Brooks'), barberRef(DEMO_BARBER_IDS.marcus, 'Marcus Bell')],
    },
    {
      id: DEMO_SERVICE_IDS.shortBackAndSides,
      name: 'Short back and sides clipper',
      description: 'Traditional short back and sides.',
      pricePence: gbp(30),
      durationMinutes: 25,
      bufferMinutes: 5,
      displayOrder: 6,
      category: 'featured',
      isActive: true,
      barberServices: [barberRef(DEMO_BARBER_IDS.jamie, 'Jamie Reed'), barberRef(DEMO_BARBER_IDS.marcus, 'Marcus Bell')],
    },
    {
      id: DEMO_SERVICE_IDS.longerHaircut,
      name: 'Longer haircut',
      description: 'Scissor work for longer lengths.',
      pricePence: gbp(65),
      durationMinutes: 60,
      bufferMinutes: 5,
      displayOrder: 7,
      category: 'styling',
      isActive: true,
      barberServices: [barberRef(DEMO_BARBER_IDS.sam, 'Sam Brooks'), barberRef(DEMO_BARBER_IDS.marcus, 'Marcus Bell')],
    },
    {
      id: DEMO_SERVICE_IDS.skinFadeBackSides,
      name: 'Skin fade back n sides only',
      description: 'Fade on back and sides, top untouched.',
      pricePence: gbp(30),
      durationMinutes: 25,
      bufferMinutes: 5,
      displayOrder: 8,
      category: 'styling',
      isActive: true,
      barberServices: [barberRef(DEMO_BARBER_IDS.alex, 'Alex Morgan'), barberRef(DEMO_BARBER_IDS.jamie, 'Jamie Reed')],
    },
    {
      id: DEMO_SERVICE_IDS.headShave,
      name: 'Head shave',
      description: 'Clean head shave with razor finish.',
      pricePence: gbp(25),
      durationMinutes: 20,
      bufferMinutes: 5,
      displayOrder: 9,
      category: 'styling',
      isActive: true,
      barberServices: [barberRef(DEMO_BARBER_IDS.marcus, 'Marcus Bell'), barberRef(DEMO_BARBER_IDS.alex, 'Alex Morgan')],
    },
    {
      id: DEMO_SERVICE_IDS.hairWash,
      name: 'Hair wash',
      description: 'Shampoo and conditioning treatment.',
      pricePence: gbp(10),
      durationMinutes: 10,
      bufferMinutes: 5,
      displayOrder: 10,
      category: 'styling',
      isActive: true,
      barberServices: ALL_BARBER_REFS,
    },
    {
      id: DEMO_SERVICE_IDS.premiumBeardTrim,
      name: 'Premium beard trim',
      description: 'Full beard sculpt with hot towel.',
      pricePence: gbp(30),
      durationMinutes: 25,
      bufferMinutes: 5,
      displayOrder: 11,
      category: 'beard styling',
      isActive: true,
      barberServices: [barberRef(DEMO_BARBER_IDS.alex, 'Alex Morgan'), barberRef(DEMO_BARBER_IDS.sam, 'Sam Brooks')],
    },
    {
      id: DEMO_SERVICE_IDS.longerBeardTrim,
      name: 'Longer beard trim',
      description: 'Shape and maintain longer beards.',
      pricePence: gbp(40),
      durationMinutes: 35,
      bufferMinutes: 5,
      displayOrder: 12,
      category: 'beard styling',
      isActive: true,
      barberServices: [barberRef(DEMO_BARBER_IDS.marcus, 'Marcus Bell'), barberRef(DEMO_BARBER_IDS.alex, 'Alex Morgan')],
    },
    {
      id: DEMO_SERVICE_IDS.luxuryWetShave,
      name: 'Luxury wet shave',
      description: 'Hot towel straight-razor shave.',
      pricePence: gbp(40),
      durationMinutes: 40,
      bufferMinutes: 5,
      displayOrder: 13,
      category: 'shaving',
      isActive: true,
      barberServices: [barberRef(DEMO_BARBER_IDS.alex, 'Alex Morgan'), barberRef(DEMO_BARBER_IDS.marcus, 'Marcus Bell')],
    },
    {
      id: DEMO_SERVICE_IDS.expressShave,
      name: 'Express shave',
      description: 'Quick razor tidy-up.',
      pricePence: gbp(25),
      durationMinutes: 20,
      bufferMinutes: 5,
      displayOrder: 14,
      category: 'shaving',
      isActive: true,
      barberServices: [barberRef(DEMO_BARBER_IDS.marcus, 'Marcus Bell'), barberRef(DEMO_BARBER_IDS.jamie, 'Jamie Reed')],
    },
    {
      id: DEMO_SERVICE_IDS.friction,
      name: 'Friction',
      description: 'Scalp friction massage.',
      pricePence: gbp(15),
      durationMinutes: 15,
      bufferMinutes: 5,
      displayOrder: 15,
      category: 'wellbeing',
      isActive: true,
      barberServices: [barberRef(DEMO_BARBER_IDS.sam, 'Sam Brooks'), barberRef(DEMO_BARBER_IDS.marcus, 'Marcus Bell')],
    },
    {
      id: DEMO_SERVICE_IDS.friction10Min,
      name: 'Friction 10 min',
      description: 'Short scalp friction treatment.',
      pricePence: gbp(10),
      durationMinutes: 10,
      bufferMinutes: 5,
      displayOrder: 16,
      category: 'wellbeing',
      isActive: true,
      barberServices: [barberRef(DEMO_BARBER_IDS.sam, 'Sam Brooks'), barberRef(DEMO_BARBER_IDS.jamie, 'Jamie Reed')],
    },
  ],
  categories: [...BOOKING_SERVICE_CATEGORY_ORDER],
};

export const demoServiceCategoriesResponse = {
  categories: [...BOOKING_SERVICE_CATEGORY_ORDER],
};
