import type { ProductSemanticProfileV2 } from '@/lib/recommendations/contracts';
import { CRITICAL_FIELD_CONFIDENCE, productProfile } from './profileHelpers';

export const DEMO_PRODUCT_PROFILES: Record<string, ProductSemanticProfileV2> = {
  'bl-product-ironclad-pomade': productProfile(
    'bl-product-ironclad-pomade',
    {
      targetAreas: ['HAIR'],
      hairLengthSuitability: 'ANY',
      productFamily: 'POMADE',
      benefits: ['HOLD', 'SHINE_FINISH'],
      holdStrength: 'STRONG',
      finish: 'SHINE',
      incompatibilities: ['HAIR_ONLY'],
      retailNeeds: ['HAIR_STYLING_CONTROL', 'HAIR_SHINE_POLISH'],
      confidence: 0.88,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_IRONCLAD_POMADE'],
      warnings: [],
    },
    {
      name: 'Ironclad Pomade',
      description: 'Firm hold pomade for sharp lines and longer-lasting structure. Light sheen, not greasy.',
      category: 'STYLING',
    },
  ),
  'bl-product-beard-balm': productProfile(
    'bl-product-beard-balm',
    {
      targetAreas: ['BEARD'],
      hairLengthSuitability: 'NOT_APPLICABLE',
      productFamily: 'BALM',
      benefits: ['BEARD_SHAPE', 'BEARD_SOFTENING'],
      holdStrength: 'LIGHT',
      finish: 'NATURAL',
      incompatibilities: ['BEARD_ONLY'],
      retailNeeds: ['BEARD_SOFTENING', 'BEARD_SHAPING'],
      confidence: 0.88,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_BEARD_BALM'],
      warnings: [],
    },
    {
      name: 'Beard Balm',
      description: 'Nourishing balm for shape and control. Softens coarser beards without a heavy cast.',
      category: 'BEARD_CARE',
    },
  ),
  'bl-product-barber-wash': productProfile(
    'bl-product-barber-wash',
    {
      targetAreas: ['HAIR'],
      hairLengthSuitability: 'ANY',
      productFamily: 'WASH_SHAMPOO',
      benefits: ['CLEANSING'],
      holdStrength: 'NONE',
      finish: 'NATURAL',
      incompatibilities: ['HAIR_ONLY'],
      retailNeeds: ['HAIR_CLEANSING'],
      confidence: 0.86,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_BARBER_WASH'],
      warnings: [],
    },
    {
      name: 'Barber Wash',
      description: 'Barbershop-strength wash for product build-up. Leaves hair ready to style.',
      category: 'HAIR_WASH',
    },
  ),
  'bl-product-essential-styling-set': productProfile(
    'bl-product-essential-styling-set',
    {
      targetAreas: ['GENERAL_GROOMING'],
      hairLengthSuitability: 'ANY',
      productFamily: 'GIFT_SET',
      benefits: ['HOLD', 'TEXTURE'],
      holdStrength: 'MEDIUM',
      finish: 'MATTE',
      incompatibilities: [],
      retailNeeds: ['GIFTING'],
      confidence: 0.8,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_ESSENTIAL_STYLING_SET'],
      warnings: [],
    },
    {
      name: 'Essential Styling Set',
      description: 'Pomade, powder and a pocket comb packed for the chair or the kit bag.',
      category: 'GIFT_SETS',
    },
  ),
  'bl-product-matte-pomade': productProfile(
    'bl-product-matte-pomade',
    {
      targetAreas: ['HAIR'],
      hairLengthSuitability: 'SHORT',
      productFamily: 'POMADE',
      benefits: ['HOLD', 'MATTE_FINISH'],
      holdStrength: 'MEDIUM',
      finish: 'MATTE',
      incompatibilities: ['HAIR_ONLY'],
      retailNeeds: ['HAIR_STYLING_CONTROL'],
      confidence: 0.88,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_MATTE_POMADE'],
      warnings: [],
    },
    {
      name: 'Matte Pomade',
      description: 'Medium hold with a clean matte finish. Easy restyle through the day without shine.',
      category: 'STYLING',
    },
  ),
  'bl-product-sea-salt-texture-spray': productProfile(
    'bl-product-sea-salt-texture-spray',
    {
      targetAreas: ['HAIR'],
      hairLengthSuitability: 'ANY',
      productFamily: 'SPRAY',
      benefits: ['TEXTURE', 'VOLUME'],
      holdStrength: 'LIGHT',
      finish: 'MATTE',
      incompatibilities: ['HAIR_ONLY'],
      retailNeeds: ['HAIR_TEXTURE_DEFINITION', 'HAIR_VOLUME'],
      confidence: 0.86,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_SEA_SALT_SPRAY'],
      warnings: [],
    },
    {
      name: 'Sea Salt Texture Spray',
      description: 'Beach-texture spray for grip and movement. Mist, scrunch, air-dry or blow-dry.',
      category: 'STYLING',
    },
  ),
  'bl-product-beard-oil': productProfile(
    'bl-product-beard-oil',
    {
      targetAreas: ['BEARD'],
      hairLengthSuitability: 'NOT_APPLICABLE',
      productFamily: 'OIL',
      benefits: ['BEARD_SOFTENING', 'BEARD_SHAPE'],
      holdStrength: 'NONE',
      finish: 'NATURAL',
      incompatibilities: ['BEARD_ONLY'],
      retailNeeds: ['BEARD_SOFTENING'],
      confidence: 0.9,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_BEARD_OIL'],
      warnings: [],
    },
    {
      name: 'Beard Oil',
      description: 'Lightweight conditioning oil that softens hair and calms skin underneath.',
      category: 'BEARD_CARE',
    },
  ),
  'bl-product-forge-styling-powder': productProfile(
    'bl-product-forge-styling-powder',
    {
      targetAreas: ['HAIR'],
      hairLengthSuitability: 'SHORT',
      productFamily: 'POWDER',
      benefits: ['TEXTURE', 'VOLUME', 'MATTE_FINISH'],
      holdStrength: 'LIGHT',
      finish: 'MATTE',
      incompatibilities: ['HAIR_ONLY'],
      retailNeeds: ['HAIR_TEXTURE_DEFINITION', 'HAIR_VOLUME'],
      confidence: 0.86,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_FORGE_POWDER'],
      warnings: [],
    },
    {
      name: 'Forge Styling Powder',
      description: 'Matte powder for root lift and grit. Tap on dry hair for instant texture.',
      category: 'STYLING',
    },
  ),
  'bl-product-fibre-paste': productProfile(
    'bl-product-fibre-paste',
    {
      targetAreas: ['HAIR'],
      hairLengthSuitability: 'SHORT',
      productFamily: 'WAX',
      benefits: ['HOLD', 'TEXTURE', 'MATTE_FINISH'],
      holdStrength: 'MEDIUM',
      finish: 'NATURAL',
      incompatibilities: ['HAIR_ONLY'],
      retailNeeds: ['HAIR_STYLING_CONTROL', 'HAIR_TEXTURE_DEFINITION'],
      confidence: 0.86,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_FIBRE_PASTE'],
      warnings: [],
    },
    {
      name: 'Fibre Paste',
      description: 'Workable fibre for separation and a natural finish. Restyles with a little heat.',
      category: 'STYLING',
    },
  ),
  'bl-product-matte-clay': productProfile(
    'bl-product-matte-clay',
    {
      targetAreas: ['HAIR'],
      hairLengthSuitability: 'SHORT',
      productFamily: 'CLAY',
      benefits: ['HOLD', 'MATTE_FINISH', 'TEXTURE'],
      holdStrength: 'STRONG',
      finish: 'MATTE',
      incompatibilities: ['HAIR_ONLY'],
      retailNeeds: ['HAIR_STYLING_CONTROL', 'HAIR_TEXTURE_DEFINITION'],
      confidence: 0.9,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_MATTE_CLAY'],
      warnings: [],
    },
    {
      name: 'Matte Clay',
      description: 'High-hold clay with a dry, low-shine finish for cropped cuts.',
      category: 'STYLING',
    },
  ),
  'bl-product-styling-cream': productProfile(
    'bl-product-styling-cream',
    {
      targetAreas: ['HAIR'],
      hairLengthSuitability: 'LONG',
      productFamily: 'CREAM',
      benefits: ['TEXTURE', 'VOLUME', 'FRIZZ_CONTROL'],
      holdStrength: 'LIGHT',
      finish: 'NATURAL',
      incompatibilities: ['HAIR_ONLY', 'FOR_LONG_HAIR_ONLY'],
      retailNeeds: ['HAIR_STYLING_CONTROL', 'HAIR_SMOOTHING_FRIZZ_CONTROL'],
      confidence: 0.86,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['DESC_LONGER_HAIR'],
      warnings: [],
    },
    {
      name: 'Styling Cream',
      description: 'Soft cream for control without crunch. Suits longer hair and a natural part.',
      category: 'STYLING',
    },
  ),
  'bl-product-daily-conditioner': productProfile(
    'bl-product-daily-conditioner',
    {
      targetAreas: ['HAIR'],
      hairLengthSuitability: 'ANY',
      productFamily: 'CONDITIONER',
      benefits: ['DETANGLING'],
      holdStrength: 'NONE',
      finish: 'NATURAL',
      incompatibilities: ['HAIR_ONLY', 'NOT_FOR_BEARD'],
      retailNeeds: ['HAIR_CONDITIONING'],
      confidence: 0.82,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_CONDITIONER'],
      warnings: [],
    },
    {
      name: 'Daily Conditioner',
      description: 'Everyday conditioner that detangles without weighing the cut down.',
      category: 'HAIR_WASH',
    },
  ),
  'bl-product-scalp-scrub': productProfile(
    'bl-product-scalp-scrub',
    {
      targetAreas: ['SCALP', 'HAIR'],
      hairLengthSuitability: 'ANY',
      productFamily: 'MASK_TREATMENT',
      benefits: ['CLEANSING'],
      holdStrength: 'NONE',
      finish: 'NATURAL',
      incompatibilities: [],
      retailNeeds: ['SCALP_CARE', 'HAIR_CLEANSING'],
      confidence: 0.88,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_SCALP_SCRUB'],
      warnings: [],
    },
    {
      name: 'Scalp Scrub',
      description: 'Weekly scrub to lift product build-up and refresh the scalp.',
      category: 'HAIR_WASH',
    },
  ),
  'bl-product-clarifying-rinse': productProfile(
    'bl-product-clarifying-rinse',
    {
      targetAreas: ['HAIR', 'SCALP'],
      hairLengthSuitability: 'ANY',
      productFamily: 'WASH_SHAMPOO',
      benefits: ['CLEANSING'],
      holdStrength: 'NONE',
      finish: 'NATURAL',
      incompatibilities: ['HAIR_ONLY'],
      retailNeeds: ['HAIR_CLEANSING', 'SCALP_CARE'],
      confidence: 0.86,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_CLARIFYING_RINSE'],
      warnings: [],
    },
    {
      name: 'Clarifying Rinse',
      description: 'A sharp rinse when pomade and powder have stacked through the week.',
      category: 'HAIR_WASH',
    },
  ),
  'bl-product-beard-wash': productProfile(
    'bl-product-beard-wash',
    {
      targetAreas: ['BEARD'],
      hairLengthSuitability: 'NOT_APPLICABLE',
      productFamily: 'WASH_SHAMPOO',
      benefits: ['CLEANSING', 'BEARD_SOFTENING'],
      holdStrength: 'NONE',
      finish: 'NATURAL',
      incompatibilities: ['BEARD_ONLY'],
      retailNeeds: ['BEARD_CLEANSING'],
      confidence: 0.84,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_BEARD_WASH'],
      warnings: [],
    },
    {
      name: 'Beard Wash',
      description: 'Gentle wash for facial hair that does not strip the skin underneath.',
      category: 'BEARD_CARE',
    },
  ),
  'bl-product-beard-butter': productProfile(
    'bl-product-beard-butter',
    {
      targetAreas: ['BEARD'],
      hairLengthSuitability: 'NOT_APPLICABLE',
      productFamily: 'BUTTER',
      benefits: ['BEARD_SOFTENING'],
      holdStrength: 'NONE',
      finish: 'NATURAL',
      incompatibilities: ['BEARD_ONLY'],
      retailNeeds: ['BEARD_SOFTENING'],
      confidence: 0.86,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_BEARD_BUTTER'],
      warnings: [],
    },
    {
      name: 'Beard Butter',
      description: 'Richer leave-in butter for longer beards that need overnight softness.',
      category: 'BEARD_CARE',
    },
  ),
  'bl-product-moustache-wax': productProfile(
    'bl-product-moustache-wax',
    {
      targetAreas: ['MOUSTACHE', 'BEARD'],
      hairLengthSuitability: 'NOT_APPLICABLE',
      productFamily: 'WAX',
      benefits: ['BEARD_SHAPE', 'HOLD'],
      holdStrength: 'STRONG',
      finish: 'NATURAL',
      incompatibilities: ['BEARD_ONLY'],
      retailNeeds: ['BEARD_SHAPING'],
      confidence: 0.84,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_MOUSTACHE_WAX'],
      warnings: [],
    },
    {
      name: 'Moustache Wax',
      description: 'Small-tin wax for a tidy moustache and a controlled curl.',
      category: 'BEARD_CARE',
    },
  ),
  'bl-product-shave-cream': productProfile(
    'bl-product-shave-cream',
    {
      targetAreas: ['SHAVE', 'FACE'],
      hairLengthSuitability: 'NOT_APPLICABLE',
      productFamily: 'CREAM',
      benefits: ['CLEANSING'],
      holdStrength: 'NONE',
      finish: 'NATURAL',
      incompatibilities: [],
      retailNeeds: ['SHAVE_PREPARATION'],
      confidence: 0.86,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_SHAVE_CREAM'],
      warnings: [],
    },
    {
      name: 'Shave Cream',
      description: 'Close-shave cream for razor work. Simple product, one formula, collect in shop.',
      category: 'SHAVE_AND_SKIN',
    },
  ),
  'bl-product-aftershave-balm': productProfile(
    'bl-product-aftershave-balm',
    {
      targetAreas: ['SHAVE', 'FACE'],
      hairLengthSuitability: 'NOT_APPLICABLE',
      productFamily: 'AFTERSHAVE_BALM',
      benefits: ['POST_SHAVE_COMFORT'],
      holdStrength: 'NONE',
      finish: 'NATURAL',
      incompatibilities: ['POST_SHAVE_ONLY'],
      retailNeeds: ['POST_SHAVE_SOOTHING'],
      confidence: 0.9,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_AFTERSHAVE'],
      warnings: [],
    },
    {
      name: 'Aftershave Balm',
      description: 'Alcohol-free balm to calm skin after a hot towel shave.',
      category: 'SHAVE_AND_SKIN',
    },
  ),
  'bl-product-face-wash': productProfile(
    'bl-product-face-wash',
    {
      targetAreas: ['FACE'],
      hairLengthSuitability: 'NOT_APPLICABLE',
      productFamily: 'WASH_SHAMPOO',
      benefits: ['CLEANSING'],
      holdStrength: 'NONE',
      finish: 'NATURAL',
      incompatibilities: [],
      retailNeeds: ['FACE_CLEANSING'],
      confidence: 0.86,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_FACE_WASH'],
      warnings: [],
    },
    {
      name: 'Face Wash',
      description: 'Daily face wash that rinses clean without tightness.',
      category: 'SHAVE_AND_SKIN',
    },
  ),
  'bl-product-daily-moisturiser': productProfile(
    'bl-product-daily-moisturiser',
    {
      targetAreas: ['FACE'],
      hairLengthSuitability: 'NOT_APPLICABLE',
      productFamily: 'MOISTURISER',
      benefits: ['POST_SHAVE_COMFORT'],
      holdStrength: 'NONE',
      finish: 'NATURAL',
      incompatibilities: [],
      retailNeeds: ['FACE_MOISTURISING'],
      confidence: 0.82,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_MOISTURISER'],
      warnings: [],
    },
    {
      name: 'Daily Moisturiser',
      description: 'Light moisturiser for skin that sees clippers, towels and product.',
      category: 'SHAVE_AND_SKIN',
    },
  ),
  'bl-product-cutting-comb': productProfile(
    'bl-product-cutting-comb',
    {
      targetAreas: ['TOOLS_ACCESSORIES'],
      hairLengthSuitability: 'NOT_APPLICABLE',
      productFamily: 'TOOL',
      benefits: ['UNKNOWN'],
      holdStrength: 'NONE',
      finish: 'UNKNOWN',
      incompatibilities: [],
      retailNeeds: ['GROOMING_TOOL'],
      confidence: 0.8,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_CUTTING_COMB'],
      warnings: [],
    },
    {
      name: 'Cutting Comb',
      description: 'Heat-resistant comb for the chair and the kit. One size, no options.',
      category: 'TOOLS',
    },
  ),
  'bl-product-boar-brush': productProfile(
    'bl-product-boar-brush',
    {
      targetAreas: ['TOOLS_ACCESSORIES'],
      hairLengthSuitability: 'NOT_APPLICABLE',
      productFamily: 'TOOL',
      benefits: ['UNKNOWN'],
      holdStrength: 'NONE',
      finish: 'UNKNOWN',
      incompatibilities: [],
      retailNeeds: ['GROOMING_TOOL'],
      confidence: 0.8,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_BOAR_BRUSH'],
      warnings: [],
    },
    {
      name: 'Boar Bristle Brush',
      description: 'Club brush for finish work and laying a pomade cut.',
      category: 'TOOLS',
    },
  ),
  'bl-product-neck-duster': productProfile(
    'bl-product-neck-duster',
    {
      targetAreas: ['TOOLS_ACCESSORIES'],
      hairLengthSuitability: 'NOT_APPLICABLE',
      productFamily: 'TOOL',
      benefits: ['UNKNOWN'],
      holdStrength: 'NONE',
      finish: 'UNKNOWN',
      incompatibilities: [],
      retailNeeds: ['GROOMING_TOOL'],
      confidence: 0.78,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_NECK_DUSTER'],
      warnings: [],
    },
    {
      name: 'Neck Duster',
      description: 'Soft duster for the finish. The same tool the chair uses.',
      category: 'TOOLS',
    },
  ),
  'bl-product-clipper-guard-set': productProfile(
    'bl-product-clipper-guard-set',
    {
      targetAreas: ['TOOLS_ACCESSORIES'],
      hairLengthSuitability: 'NOT_APPLICABLE',
      productFamily: 'TOOL',
      benefits: ['UNKNOWN'],
      holdStrength: 'NONE',
      finish: 'UNKNOWN',
      incompatibilities: [],
      retailNeeds: ['GROOMING_TOOL'],
      confidence: 0.78,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_CLIPPER_GUARD_SET'],
      warnings: [],
    },
    {
      name: 'Clipper Guard Set',
      description: 'Numbered guards for home tidy-ups between appointments.',
      category: 'TOOLS',
    },
  ),
  'bl-product-beard-kit': productProfile(
    'bl-product-beard-kit',
    {
      targetAreas: ['GENERAL_GROOMING'],
      hairLengthSuitability: 'NOT_APPLICABLE',
      productFamily: 'GIFT_SET',
      benefits: ['BEARD_SOFTENING', 'BEARD_SHAPE'],
      holdStrength: 'NONE',
      finish: 'NATURAL',
      incompatibilities: [],
      retailNeeds: ['GIFTING'],
      confidence: 0.8,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_BEARD_KIT'],
      warnings: [],
    },
    {
      name: 'Beard Kit',
      description: 'Wash, oil and balm together for a full beard routine.',
      category: 'GIFT_SETS',
    },
  ),
  'bl-product-travel-grooming-set': productProfile(
    'bl-product-travel-grooming-set',
    {
      targetAreas: ['GENERAL_GROOMING'],
      hairLengthSuitability: 'ANY',
      productFamily: 'GIFT_SET',
      benefits: ['CLEANSING'],
      holdStrength: 'NONE',
      finish: 'NATURAL',
      incompatibilities: [],
      retailNeeds: ['GIFTING'],
      confidence: 0.78,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_TRAVEL_GROOMING_SET'],
      warnings: [],
    },
    {
      name: 'Travel Grooming Set',
      description: 'Wash, cream and a comb sized for a week away.',
      category: 'GIFT_SETS',
    },
  ),
  'bl-product-shop-gift-box': productProfile(
    'bl-product-shop-gift-box',
    {
      targetAreas: ['GENERAL_GROOMING'],
      hairLengthSuitability: 'ANY',
      productFamily: 'GIFT_SET',
      benefits: ['HOLD'],
      holdStrength: 'MEDIUM',
      finish: 'MATTE',
      incompatibilities: [],
      retailNeeds: ['GIFTING'],
      confidence: 0.78,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_SHOP_GIFT_BOX'],
      warnings: [],
    },
    {
      name: 'Shop Gift Box',
      description: 'A ready-to-collect box: styling, wash and a finishing tool.',
      category: 'GIFT_SETS',
    },
  ),
  'bl-product-hot-towel-kit': productProfile(
    'bl-product-hot-towel-kit',
    {
      targetAreas: ['GENERAL_GROOMING'],
      hairLengthSuitability: 'NOT_APPLICABLE',
      productFamily: 'GIFT_SET',
      benefits: ['POST_SHAVE_COMFORT'],
      holdStrength: 'NONE',
      finish: 'NATURAL',
      incompatibilities: [],
      retailNeeds: ['GIFTING'],
      confidence: 0.78,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_HOT_TOWEL_KIT'],
      warnings: [],
    },
    {
      name: 'Hot Towel Home Kit',
      description:
        'Towel warmer, barber towels, refresh spray and shave accessories for a slower shave at home.',
      category: 'GIFT_SETS',
    },
  ),
};
