import type { ServiceSemanticProfileV2 } from '@/lib/recommendations/contracts';
import { CRITICAL_FIELD_CONFIDENCE, serviceProfile } from './profileHelpers';

export const DEMO_SERVICE_PROFILES: Record<string, ServiceSemanticProfileV2> = {
  'bl-svc-haircut-finish': serviceProfile(
    'bl-svc-haircut-finish',
    {
      targetAreas: ['HAIR'],
      typicalHairLength: 'UNKNOWN',
      techniques: ['SCISSOR_CUT', 'CLIPPER_CUT'],
      outcomes: ['SHAPE_STRUCTURE', 'NEAT_FINISH'],
      aftercareNeeds: ['DAILY_STYLING'],
      incompatibilities: [],
      retailNeeds: ['HAIR_STYLING_CONTROL'],
      confidence: 0.88,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_CLASSIC_CUT_FINISH'],
      warnings: [],
    },
    {
      name: 'Classic Cut & Finish',
      description: 'A tailored cut, finished and styled for the way you wear it.',
      category: 'cuts & fades',
    },
  ),
  'bl-svc-skin-fade': serviceProfile(
    'bl-svc-skin-fade',
    {
      targetAreas: ['HAIR'],
      typicalHairLength: 'SHORT',
      techniques: ['SKIN_FADE'],
      outcomes: ['SHAPE_STRUCTURE', 'TEXTURE_DEFINITION'],
      aftercareNeeds: ['DAILY_STYLING'],
      incompatibilities: [],
      retailNeeds: ['HAIR_STYLING_CONTROL', 'HAIR_TEXTURE_DEFINITION'],
      confidence: 0.9,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_SKIN_FADE'],
      warnings: [],
    },
    {
      name: 'Skin Fade',
      description: 'A seamless fade taken down to skin with a sharp, structured finish.',
      category: 'cuts & fades',
    },
  ),
  'bl-svc-taper-fade': serviceProfile(
    'bl-svc-taper-fade',
    {
      targetAreas: ['HAIR'],
      typicalHairLength: 'SHORT',
      techniques: ['TAPER_FADE'],
      outcomes: ['SHAPE_STRUCTURE', 'NEAT_FINISH'],
      aftercareNeeds: ['DAILY_STYLING'],
      incompatibilities: [],
      retailNeeds: ['HAIR_STYLING_CONTROL', 'HAIR_TEXTURE_DEFINITION'],
      confidence: 0.88,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_TAPER_FADE'],
      warnings: [],
    },
    {
      name: 'Taper Fade',
      description: 'A clean low taper through the temples and neckline with natural length above.',
      category: 'cuts & fades',
    },
  ),
  'bl-svc-scissor-cut': serviceProfile(
    'bl-svc-scissor-cut',
    {
      targetAreas: ['HAIR'],
      typicalHairLength: 'LONG',
      techniques: ['SCISSOR_CUT'],
      outcomes: ['VOLUME', 'TEXTURE_DEFINITION', 'NEAT_FINISH'],
      aftercareNeeds: ['DAILY_STYLING'],
      incompatibilities: [],
      retailNeeds: ['HAIR_STYLING_CONTROL', 'HAIR_SMOOTHING_FRIZZ_CONTROL', 'HAIR_CONDITIONING'],
      confidence: 0.88,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_SCISSOR_CUT'],
      warnings: [],
    },
    {
      name: 'Scissor Cut / Longer Hair',
      description: 'Precision scissor work for longer shapes, movement and a natural finish.',
      category: 'cuts & fades',
    },
  ),
  'bl-svc-buzz-cut': serviceProfile(
    'bl-svc-buzz-cut',
    {
      targetAreas: ['HAIR', 'SCALP'],
      typicalHairLength: 'SHORT',
      techniques: ['BUZZ_CUT', 'CLIPPER_CUT'],
      outcomes: ['NEAT_FINISH', 'SHAPE_STRUCTURE'],
      aftercareNeeds: ['NONE'],
      incompatibilities: [],
      retailNeeds: ['HAIR_STYLING_CONTROL', 'SCALP_CARE'],
      confidence: 0.86,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_BUZZ_CUT'],
      warnings: [],
    },
    {
      name: 'Buzz Cut',
      description: 'A clean clipper cut using one length, finished around the edges and neckline.',
      category: 'cuts & fades',
    },
  ),
  'bl-svc-restyle': serviceProfile(
    'bl-svc-restyle',
    {
      targetAreas: ['HAIR'],
      typicalHairLength: 'LONG',
      techniques: ['SCISSOR_CUT'],
      outcomes: ['VOLUME', 'TEXTURE_DEFINITION'],
      aftercareNeeds: ['DAILY_STYLING'],
      incompatibilities: [],
      retailNeeds: [
        'HAIR_STYLING_CONTROL',
        'HAIR_SMOOTHING_FRIZZ_CONTROL',
        'HAIR_VOLUME',
        'HAIR_CONDITIONING',
      ],
      confidence: 0.85,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_RESTYLE'],
      warnings: [],
    },
    {
      name: 'Restyle',
      description: 'Extra consultation and cutting time for a significant change of shape or length.',
      category: 'cuts & fades',
    },
  ),
  'bl-svc-beard-trim': serviceProfile(
    'bl-svc-beard-trim',
    {
      targetAreas: ['BEARD'],
      typicalHairLength: 'NOT_APPLICABLE',
      techniques: ['BEARD_TRIM'],
      outcomes: ['BEARD_DEFINITION', 'NEAT_FINISH'],
      aftercareNeeds: ['BEARD_DAILY'],
      incompatibilities: [],
      retailNeeds: ['BEARD_SOFTENING', 'BEARD_SHAPING', 'BEARD_CLEANSING'],
      confidence: 0.9,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_BEARD_TRIM'],
      warnings: [],
    },
    {
      name: 'Beard Trim & Shape',
      description: 'A tidy beard trim with defined lines and a balanced shape.',
      category: 'beard & shave',
    },
  ),
  'bl-svc-beard-sculpt': serviceProfile(
    'bl-svc-beard-sculpt',
    {
      targetAreas: ['BEARD'],
      typicalHairLength: 'NOT_APPLICABLE',
      techniques: ['BEARD_SCULPT'],
      outcomes: ['BEARD_DEFINITION', 'SKIN_COMFORT_POST_SHAVE'],
      aftercareNeeds: ['BEARD_DAILY', 'POST_SHAVE_SOOTHING'],
      incompatibilities: [],
      retailNeeds: ['BEARD_SOFTENING', 'BEARD_SHAPING', 'POST_SHAVE_SOOTHING'],
      confidence: 0.88,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_BEARD_SCULPT'],
      warnings: [],
    },
    {
      name: 'Beard Sculpt & Hot Towel',
      description: 'Detailed beard sculpting finished with a hot towel for a clean close.',
      category: 'beard & shave',
    },
  ),
  'bl-svc-hot-towel-shave': serviceProfile(
    'bl-svc-hot-towel-shave',
    {
      targetAreas: ['SHAVE', 'FACE'],
      typicalHairLength: 'NOT_APPLICABLE',
      techniques: ['HOT_TOWEL_SHAVE'],
      outcomes: ['SKIN_COMFORT_POST_SHAVE', 'NEAT_FINISH'],
      aftercareNeeds: ['POST_SHAVE_SOOTHING'],
      incompatibilities: [],
      retailNeeds: ['POST_SHAVE_SOOTHING', 'SHAVE_PREPARATION'],
      confidence: 0.88,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_HOT_TOWEL'],
      warnings: [],
    },
    {
      name: 'Hot Towel Wet Shave',
      description: 'A traditional hot towel wet shave with a close, clean finish.',
      category: 'beard & shave',
    },
  ),
  'bl-svc-line-up': serviceProfile(
    'bl-svc-line-up',
    {
      targetAreas: ['HAIR', 'BEARD'],
      typicalHairLength: 'SHORT',
      techniques: ['LINE_UP'],
      outcomes: ['NEAT_FINISH', 'SHAPE_STRUCTURE'],
      aftercareNeeds: ['DAILY_STYLING'],
      incompatibilities: [],
      retailNeeds: ['HAIR_STYLING_CONTROL', 'BEARD_SHAPING'],
      confidence: 0.84,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_LINE_UP'],
      warnings: [],
    },
    {
      name: 'Line-Up & Neck Clean',
      description: 'A sharp hairline, beard line and neck clean-up without a full cut.',
      category: 'beard & shave',
    },
  ),
  'bl-svc-haircut-beard': serviceProfile(
    'bl-svc-haircut-beard',
    {
      targetAreas: ['HAIR', 'BEARD'],
      typicalHairLength: 'UNKNOWN',
      techniques: ['COMBO_HAIR_BEARD', 'SCISSOR_CUT', 'BEARD_TRIM'],
      outcomes: ['SHAPE_STRUCTURE', 'BEARD_DEFINITION', 'NEAT_FINISH'],
      aftercareNeeds: ['DAILY_STYLING', 'BEARD_DAILY'],
      incompatibilities: [],
      retailNeeds: ['HAIR_STYLING_CONTROL', 'BEARD_SOFTENING', 'BEARD_SHAPING'],
      confidence: 0.9,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_HAIRCUT_BEARD'],
      warnings: [],
    },
    {
      name: 'Haircut & Beard',
      description: 'A complete haircut and beard-shaping appointment.',
      category: 'hair & beard combos',
    },
  ),
  'bl-svc-skin-fade-beard': serviceProfile(
    'bl-svc-skin-fade-beard',
    {
      targetAreas: ['HAIR', 'BEARD'],
      typicalHairLength: 'SHORT',
      techniques: ['COMBO_HAIR_BEARD', 'SKIN_FADE', 'BEARD_TRIM'],
      outcomes: ['SHAPE_STRUCTURE', 'TEXTURE_DEFINITION', 'BEARD_DEFINITION'],
      aftercareNeeds: ['DAILY_STYLING', 'BEARD_DAILY'],
      incompatibilities: [],
      retailNeeds: [
        'HAIR_STYLING_CONTROL',
        'HAIR_TEXTURE_DEFINITION',
        'BEARD_SOFTENING',
        'BEARD_SHAPING',
      ],
      confidence: 0.9,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_SKIN_FADE_BEARD'],
      warnings: [],
    },
    {
      name: 'Skin Fade & Beard',
      description: 'A skin fade with a full beard trim and shape in one visit.',
      category: 'hair & beard combos',
    },
  ),
  'bl-svc-taper-fade-beard': serviceProfile(
    'bl-svc-taper-fade-beard',
    {
      targetAreas: ['HAIR', 'BEARD'],
      typicalHairLength: 'SHORT',
      techniques: ['COMBO_HAIR_BEARD', 'TAPER_FADE', 'BEARD_TRIM'],
      outcomes: ['SHAPE_STRUCTURE', 'BEARD_DEFINITION', 'NEAT_FINISH'],
      aftercareNeeds: ['DAILY_STYLING', 'BEARD_DAILY'],
      incompatibilities: [],
      retailNeeds: ['HAIR_STYLING_CONTROL', 'BEARD_SOFTENING', 'BEARD_SHAPING'],
      confidence: 0.88,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_TAPER_FADE_BEARD'],
      warnings: [],
    },
    {
      name: 'Taper Fade & Beard',
      description: 'A taper fade paired with a considered beard trim and finish.',
      category: 'hair & beard combos',
    },
  ),
  'bl-svc-full-grooming': serviceProfile(
    'bl-svc-full-grooming',
    {
      targetAreas: ['HAIR', 'BEARD', 'FACE'],
      typicalHairLength: 'UNKNOWN',
      techniques: ['COMBO_HAIR_BEARD', 'WASH_STYLE'],
      outcomes: ['SHAPE_STRUCTURE', 'BEARD_DEFINITION', 'NEAT_FINISH', 'HYDRATION'],
      aftercareNeeds: ['DAILY_STYLING', 'BEARD_DAILY'],
      incompatibilities: [],
      retailNeeds: [
        'HAIR_STYLING_CONTROL',
        'HAIR_CLEANSING',
        'BEARD_SOFTENING',
        'FACE_MOISTURISING',
      ],
      confidence: 0.86,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_FULL_GROOMING'],
      warnings: [],
    },
    {
      name: 'Full Grooming Experience',
      description: 'Hair, beard and finishing time for a complete reset.',
      category: 'hair & beard combos',
    },
  ),
  'bl-svc-grey-blending': serviceProfile(
    'bl-svc-grey-blending',
    {
      targetAreas: ['HAIR'],
      typicalHairLength: 'ANY',
      techniques: ['COLOUR_GREY_BLEND'],
      outcomes: ['NEAT_FINISH'],
      aftercareNeeds: ['NONE'],
      incompatibilities: [],
      retailNeeds: ['COLOUR_MAINTENANCE'],
      confidence: 0.82,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_GREY_BLENDING'],
      warnings: [],
    },
    {
      name: 'Grey Blending',
      description: 'Soft colour blending to reduce grey without a solid dye look.',
      category: 'grooming & care',
    },
  ),
  'bl-svc-scalp-treatment': serviceProfile(
    'bl-svc-scalp-treatment',
    {
      targetAreas: ['SCALP', 'HAIR'],
      typicalHairLength: 'ANY',
      techniques: ['SCALP_CLEANSE'],
      outcomes: ['HYDRATION', 'OIL_CONTROL'],
      aftercareNeeds: ['SCALP_ROUTINE'],
      incompatibilities: [],
      retailNeeds: ['SCALP_CARE', 'HAIR_CLEANSING'],
      confidence: 0.88,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_SCALP_TREATMENT'],
      warnings: [],
    },
    {
      name: 'Scalp Cleanse & Treatment',
      description: 'A focused scalp cleanse and treatment to reset the hair and skin.',
      category: 'grooming & care',
    },
  ),
  'bl-svc-express-facial': serviceProfile(
    'bl-svc-express-facial',
    {
      targetAreas: ['FACE'],
      typicalHairLength: 'NOT_APPLICABLE',
      techniques: ['FACIAL_GROOMING'],
      outcomes: ['HYDRATION', 'NEAT_FINISH'],
      aftercareNeeds: ['NONE'],
      incompatibilities: [],
      retailNeeds: ['FACE_CLEANSING', 'FACE_MOISTURISING'],
      confidence: 0.88,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_EXPRESS_FACIAL'],
      warnings: [],
    },
    {
      name: 'Express Facial',
      description: 'A short facial to cleanse, refresh and settle the skin.',
      category: 'grooming & care',
    },
  ),
  'bl-svc-wash-style-finish': serviceProfile(
    'bl-svc-wash-style-finish',
    {
      targetAreas: ['HAIR'],
      typicalHairLength: 'ANY',
      techniques: ['WASH_STYLE'],
      outcomes: ['NEAT_FINISH', 'TEXTURE_DEFINITION'],
      aftercareNeeds: ['DAILY_STYLING'],
      incompatibilities: [],
      retailNeeds: ['HAIR_CLEANSING', 'HAIR_CONDITIONING', 'HAIR_STYLING_CONTROL'],
      confidence: 0.86,
      fieldConfidence: CRITICAL_FIELD_CONFIDENCE,
      evidenceCodes: ['NAME_WASH_STYLE_FINISH'],
      warnings: [],
    },
    {
      name: 'Wash, Style & Finish',
      description: 'A wash, blow-dry and finish without a cut.',
      category: 'grooming & care',
    },
  ),
};
