/** Official Nearcut UK facts; checked 8 October 2026. Never assume a quoted subscription price. */
export const NEARCUT_FACTS_CHECKED_ISO = '2026-10-08';
export const NEARCUT_FACTS_CHECKED_DATE = '8 October 2026';
export const NEARCUT_SOURCES = [
  {label:'Nearcut UK pricing',url:'https://nearcut.com/en-GB/pricing',supports:'Free for You, Subscription, booking charges, websites and business boosters'},
  {label:'Nearcut Help Centre: online payments',url:'https://help.nearcut.com/en/articles/5672099-about-online-payments-and-how-to-set-it-up',supports:'optional deposits, prepaid appointments and payment processing rates'},
  {label:'Nearcut Help Centre: memberships',url:'https://help.nearcut.com/en/articles/5107569-how-to-create-a-membership-scheme',supports:'memberships as an additional Nearcut capability'},
] as const;
export const NEARCUT_TRADEMARK_DISCLAIMER = 'Nearcut is a trademark of its respective owner. KERSIVO is not affiliated with, endorsed by or sponsored by Nearcut.';
export const NEARCUT_COMPARISON_FOOTNOTE = 'Nearcut information is based on its official UK pricing page and Help Centre, checked 8 October 2026. Pricing and features can change.';
export const NEARCUT_COMPARE_SECTIONS = [
{id:'bookings',title:'Bookings',subtitle:'Scheduling, confirmations and booking journeys.',nearcutLead:'A barber-focused online booking service with a personalised booking site.',nearcutPoints:['Online booking, availability and staff schedules','Personalised booking website and social Book Now integration','Email confirmations and appointment reminders','Waitlist cancellation features'],kersivoLead:'One booking engine shared across Starter and Full.',kersivoPoints:['Up to four bookable barbers on Starter; expanded team on Full','Hosted booking page on Starter; full branded website on Full','Email confirmations and reminders on both plans','Manual booking and staff availability management']},
{id:'payments',title:'Payments & Deposits',subtitle:'Compare payment models and client charges.',nearcutLead:'Free for You puts a booking charge on online customers; Subscription removes that client booking charge.',nearcutPoints:['Free for You: £0/month to the shop, with a separate customer booking charge','Nearcut advertises £1.50 as an illustrative booking charge on its pricing page','Subscription: quote-based monthly price, with no customer booking charge','Online prepayments and deposits; check the applicable payment-processing terms'],kersivoLead:'No KERSIVO booking charge or percentage commission.',kersivoPoints:['Starter: £0/month; customer pays £5 deposit or full service price online','Both plans: 0% KERSIVO commission; standard Stripe processing fees apply','Full: £39/month per location with selectable booking payment modes','Full can offer Pay at shop, deposits or full payment']},
{id:'brand',title:'Brand & Domain',subtitle:'How each solution presents your shop.',nearcutLead:'Nearcut already supports customised websites for barbershops.',nearcutPoints:['Personalised booking website included in its plans','Subscription advertises a custom website or integration with an existing website','Facebook and Instagram Book Now integration','Nearcut is not a marketplace selling competitor placements'],kersivoLead:'A staged path from hosted bookings to an own-domain experience.',kersivoPoints:['Starter uses a KERSIVO-hosted booking page','Full includes a branded website on your own standard domain','Full includes a retail pickup experience on the site','Direct bookings without a consumer marketplace']},
{id:'retail',title:'Retail & Growth Tools',subtitle:'Compare optional growth features and retail.',nearcutLead:'Nearcut offers Business Boosters on subscription.',nearcutPoints:['Optional product sales and stock-management booster','Other boosters include memberships, loyalty and gift vouchers','Individual booster prices and availability should be checked with Nearcut','Nearcut has a broader set of add-on tools than KERSIVO in some areas'],kersivoLead:'Retail pickup included in Full KERSIVO.',kersivoPoints:['Sell grooming products online for in-shop collection on Full','Product and order management on Full','No shipping or full inventory management is claimed','0% KERSIVO retail commission; Stripe processing fees apply']},
{id:'clients',title:'Clients',subtitle:'Customer records and repeat visits.',nearcutLead:'Customer records and optional loyalty/membership features.',nearcutPoints:['Online customer booking accounts','Customer history and preferences in booking workflows','Optional memberships and loyalty through Business Boosters'],kersivoLead:'Core contacts on Starter and advanced client management on Full.',kersivoPoints:['Starter Clients Core and rolling 90-day booking history','Full Advanced Clients / CRM','Full retained history, notes and reporting where supported']},
{id:'reports',title:'Reports & Shop Operations',subtitle:'Business visibility beyond the calendar.',nearcutLead:'Business reporting and additional features vary by plan and boosters.',nearcutPoints:['Scheduling and operational booking workflows','Optional growth and retail capabilities through Business Boosters','Request plan-specific reporting details directly from Nearcut'],kersivoLead:'One dashboard with reports available on Full.',kersivoPoints:['Bookings, Team and Services on Starter','Reports and Retail Sales modules on Full','Full subscription is a flat £39/month per location']},
] as const;
