/** UK Phorest comparison facts checked 8 October 2026 against official pages. */
export const PHOREST_FACTS_CHECKED_ISO = '2026-10-08';
export const PHOREST_FACTS_CHECKED_DATE = '8 October 2026';
export const PHOREST_SOURCES = [
 {id:'pricing',label:'Phorest UK pricing and plans',url:'https://www.phorest.com/gb/pricing/',supports:'Quote-based commercial model, plans and their included or optional capabilities'},
 {id:'features',label:'Phorest UK product features',url:'https://www.phorest.com/gb/features/',supports:'Booking, CRM, email and SMS, branded booking app, POS and marketing'},
 {id:'booking',label:'Phorest online booking and deposits',url:'https://www.phorest.com/gb/features/online-booking/',supports:'Bookings through websites and social platforms, deposits and custom booking rules'},
] as const;
export const PHOREST_TRADEMARK_DISCLAIMER='Phorest is a trademark of its respective owner. KERSIVO is not affiliated with, endorsed by or sponsored by Phorest.';
export const PHOREST_COMPARISON_FOOTNOTE='Phorest information is based on official UK product and pricing pages checked 8 October 2026. Prices, plans and features may change. Request a quote for current Phorest pricing.';
export const PHOREST_COMPARE_SECTIONS=[
{id:'bookings',title:'Bookings',subtitle:'Booking pages, appointments and reminders.',phorestLead:'An established salon platform with online appointment booking.',phorestPoints:['Booking through a website, social media and branded app','Online deposits and booking rules','SMS and email appointment communications','Scheduling, rebooking and team calendars'],kersivoLead:'Barber-focused bookings from a free entry plan.',kersivoPoints:['Starter: £0/month for up to four active bookable barbers','Starter: hosted booking page and automated email reminders','Full: own branded website and standard domain','Full: SMS reminders subject to allowance']},
{id:'payments',title:'Payments & Deposits',subtitle:'What clients can pay and when.',phorestLead:'Flexible salon payment and deposit options.',phorestPoints:['Online deposits with configurable rules','Integrated salon POS and PhorestPay options','Confirm payment-processing charges in your individual quote'],kersivoLead:'Clear KERSIVO subscription and card-fee separation.',kersivoPoints:['Starter: £5 online deposit or full upfront payment for public bookings','Full: configurable Pay at shop, deposits or full payment','0% KERSIVO commission on booking payments','Standard Stripe processing fees still apply']},
{id:'brand',title:'Brand & Domain',subtitle:'Where your customer experience lives.',phorestLead:'Online bookings integrated with websites and a branded client app.',phorestPoints:['Online booking integration with the shop website','Branded booking app available depending on plan and options','Website and domain arrangements should be confirmed in the quote'],kersivoLead:'An own-domain branded website in Full.',kersivoPoints:['Starter: booking page hosted by KERSIVO','Full: branded barbershop website and one standard domain','Your identity stays central to the Full booking experience','No KERSIVO consumer marketplace']},
{id:'retail',title:'Retail & Marketing',subtitle:'Growth tools, products and sales.',phorestLead:'A comprehensive salon marketing and retail stack.',phorestPoints:['Salon POS and inventory management','Email/SMS marketing, loyalty and retention features','Online selling options; exact plan scope varies'],kersivoLead:'Focused product pickup and business operation on Full.',kersivoPoints:['Retail pickup shop with online payments on Full','Product/order tools on Full; not full stock management','0% KERSIVO commission on Full retail payments','No claim to match Phorest’s wider marketing toolset']},
{id:'clients',title:'Clients',subtitle:'Customer records and follow-up.',phorestLead:'Established salon client-management features.',phorestPoints:['Client records and appointment history','Marketing and rebooking tools','Client management linked with salon operations'],kersivoLead:'Clients Core or advanced management by plan.',kersivoPoints:['Starter: Clients Core and 90-day past booking history','Full: Advanced Clients / CRM and retained full history','Direct client booking experience in the Full website']},
{id:'reports',title:'Reports & Operations',subtitle:'Performance visibility and day-to-day running.',phorestLead:'Broader salon management and reporting capabilities.',phorestPoints:['Staff management and scheduling','Business reports and stock/POS workflows','More advanced salon-wide tools than KERSIVO in several areas'],kersivoLead:'Barber-focused workflow with clear upgrade path.',kersivoPoints:['Bookings, Team and Services in Starter','Full: reporting, retail orders and sales','£39/month per location for Full, fair-use terms apply']},
] as const;
export type PhorestCompareSectionId=(typeof PHOREST_COMPARE_SECTIONS)[number]['id'];
