import { getPublicSiteUrl } from '@/lib/setup/siteUrl';
export const SQUARE_ALTERNATIVE_PAGE_PATH='/square-appointments-alternative';
export const SQUARE_ALTERNATIVE_TITLE='Square Appointments Alternative for UK Barbers | KERSIVO';
export const SQUARE_ALTERNATIVE_DESCRIPTION='Looking for a Square Appointments alternative in the UK? Compare Free, Plus and Premium pricing, card fees, websites, deposits and KERSIVO for barbers.';
export const SQUARE_ALTERNATIVE_LAST_UPDATED_ISO='2026-10-08';
export const SQUARE_ALTERNATIVE_LAST_UPDATED_LABEL='8 October 2026';
export const SQUARE_ALTERNATIVE_FAQ_ITEMS: {question:string;answer:string}[] = [
{question:'Is KERSIVO a Square Appointments alternative for UK barbers?',answer:'Yes. KERSIVO Starter provides a hosted booking page for up to four active bookable barbers at £0/month. Full KERSIVO is £39/month per physical location and includes a full branded barbershop website, standard domain, advanced clients, reports, retail pickup and SMS reminders.'},
{question:'Is Square Appointments free in the UK?',answer:'Yes. Square Appointments Free has a £0 monthly subscription for a single location, with unlimited staff calendars and booking features. Square card-processing charges still apply when you take payments.'},
{question:'How much does Square Appointments cost in the UK?',answer:'Square Appointments currently lists Free at £0, Plus at £29/month per location and Premium at £69/month per location. Card-processing charges are separate. Check Square’s UK pricing page for the latest terms and any taxes or additions.'},
{question:'Does Square Appointments charge per barber?',answer:'Square currently advertises unlimited staff calendars on Free, Plus and Premium. Its published UK subscriptions are listed by location rather than by barber. KERSIVO Starter supports up to four active bookable barbers; Full has expanded team capacity at a flat £39/month per location, subject to fair use.'},
{question:'How much are Square payment processing fees?',answer:'Square lists 1.75% for UK in-person cards on Free and 1.6% on Plus or Premium. Square Online/Online Checkout/eCommerce UK-card processing is advertised at 1.4% + 25p, while Card on File/manual payments use a separate published 2.5% rate. The rate for a particular Square Appointments deposit depends on its actual payment flow and must not be assumed. KERSIVO uses Stripe fees, not Square rates.'},
{question:'Does Square Appointments support deposits?',answer:'Yes. Square documents fixed-amount and percentage deposits across Free, Plus and Premium. KERSIVO Starter requires a £5 online deposit or full payment for public bookings, while Full offers owner-selected payment modes including Pay at shop.'},
{question:'Does Square Appointments offer SMS reminders?',answer:'Yes. Square Appointments Free advertises automatic text and email reminders. KERSIVO Starter includes email reminders; SMS appointment reminders are a Full KERSIVO feature subject to its allowance policy.'},
{question:'What is the difference between Square Appointments and KERSIVO?',answer:'Square combines appointments with a wider POS and payments ecosystem, including in-person card hardware. KERSIVO focuses on independent barbershops: Starter offers a hosted booking page at £0/month, and Full centres bookings, a complete website and retail pickup on your shop domain. KERSIVO does not replace Square’s POS hardware.'},
{question:'Can I move my clients from Square Appointments to KERSIVO?',answer:'Square documents exporting the Customer Directory as CSV. KERSIVO can help review and migrate usable supported data. Future appointments, saved cards and every historical field are not guaranteed to transfer, so check your Square exports before switching.'},
{question:'Can I keep Square live while changing systems?',answer:'Yes. Keep Square running while your KERSIVO setup is prepared. Confirm the exported data, services and upcoming appointments, then review and approve the new booking flow before redirecting public booking links.'},
{question:'Is KERSIVO cheaper than Square Appointments?',answer:'Not always. Square Free is also £0/month, and Square Plus is £29/month compared with Full KERSIVO at £39/month. Price alone is not the key difference: compare website/domain scope, POS needs, plan features, card fees and the total booking experience.'},
{question:'Do clients need an app to book through KERSIVO?',answer:'No. Starter provides a browser-based hosted booking page, and Full includes browser-based booking on your own branded website.'},
{question:'Does Square Appointments have a marketplace?',answer:'Square Appointments offers online booking websites, including a free Square Online website option, and integrates with POS and payments. KERSIVO likewise does not operate a consumer appointment-discovery marketplace.'},
{question:'Can I try KERSIVO before switching?',answer:'Yes. Explore the live KERSIVO demo to see a booking flow, dashboard and Full retail pickup experience before choosing a plan.'}
];
export function buildSquareAlternativeFaqJsonLd():Record<string,unknown>{
 const pageUrl=getPublicSiteUrl()+SQUARE_ALTERNATIVE_PAGE_PATH;
 return {'@context':'https://schema.org','@type':'FAQPage','@id':pageUrl+'#faq',mainEntity:SQUARE_ALTERNATIVE_FAQ_ITEMS.map(i=>({'@type':'Question',name:i.question,acceptedAnswer:{'@type':'Answer',text:i.answer}}))};
}
