import { getPublicSiteUrl } from '@/lib/setup/siteUrl';
export const TREATWELL_ALTERNATIVE_PAGE_PATH = '/treatwell-alternative';
export const TREATWELL_ALTERNATIVE_TITLE = 'Treatwell Alternative UK | Pricing & Fees | KERSIVO';
export const TREATWELL_ALTERNATIVE_DESCRIPTION = 'Compare Treatwell vs KERSIVO for UK barbers: 35% first marketplace booking commission, direct bookings, deposits, websites and pricing.';
export const TREATWELL_ALTERNATIVE_LAST_UPDATED_ISO = '2026-10-08';
export const TREATWELL_ALTERNATIVE_LAST_UPDATED_LABEL = '8 October 2026';
export const TREATWELL_ALTERNATIVE_FAQ_ITEMS = [
{question:'Is KERSIVO a Treatwell alternative for UK barbers?',answer:'Yes. KERSIVO offers direct booking software for independent UK barbershops. Starter is £0/month for up to four bookable barbers; Full is £39/month per location with a branded website and standard domain. Unlike Treatwell, KERSIVO does not operate a consumer marketplace.'},
{question:'How much commission does Treatwell charge in the UK?',answer:'Treatwell publicly lists 35% plus VAT on eligible new-client bookings introduced through its marketplace, subject to venue location and partner agreement. Its September 2026 terms define new versus repeat bookings, including cases where a customer has not completed an appointment within the last 365 days. The published rate is not charged on every booking.'},
{question:'Does Treatwell charge commission on repeat bookings?',answer:'Treatwell’s UK pricing page advertises 0% marketplace commission for qualifying repeat appointments and direct bookings. Its terms specify which visits count as repeat, including a 365-day successful-appointment condition; online payment processing can still apply.'},
{question:'Are Treatwell website and social bookings commission-free?',answer:'Treatwell says bookings made directly through a salon’s website or social booking integrations are commission-free. A separate online prepayment processing fee may still apply.'},
{question:'How much does Treatwell charge for online prepayments?',answer:'Treatwell lists 2.5% plus VAT for online prepayment processing on its public UK pricing page. This is separate from qualifying marketplace new-client acquisition commission.'},
{question:'Is Treatwell free to use?',answer:'Treatwell’s UK Freelancer and Advanced plans advertise Start for free, but the page does not publish a universal permanent £0 monthly price, and its FAQ refers to a monthly fee. Ask for your venue-specific price and agreement.'},
{question:'Is KERSIVO Starter really free?',answer:'KERSIVO Starter has no monthly subscription for up to four active bookable barbers at one location. Public appointments require a £5 deposit towards the service or full online payment using a connected Stripe account. Standard Stripe processing fees apply.'},
{question:'Does KERSIVO charge commission on bookings?',answer:'KERSIVO charges 0% KERSIVO platform commission on bookings under Starter and Full. Standard Stripe processing fees still apply to card payments.'},
{question:'Can I get my own website with KERSIVO?',answer:'Full KERSIVO includes a branded barbershop website and one standard domain for £39/month per physical location. Starter uses a KERSIVO-hosted booking page.'},
{question:'Does KERSIVO offer marketplace discovery like Treatwell?',answer:'No. Treatwell can help you find customers via its marketplace. KERSIVO focuses on direct bookings via your own website, Google profile, social accounts and shop QR code.'},
{question:'Can I migrate clients and bookings from Treatwell?',answer:'KERSIVO can help assess compatible export data, including supported CSV exports. Check with Treatwell exactly what can be exported; a complete automatic client or appointment migration cannot be guaranteed.'},
{question:'Can I keep Treatwell live until KERSIVO is ready?',answer:'You can prepare a future KERSIVO setup while keeping your existing bookings accessible. However, Treatwell’s September 2026 terms restrict the use of other third-party software to enable customer bookings. Check your agreement before operating both public booking systems in parallel, and plan a controlled cutover.'},
{question:'Which system is better for an independent barbershop?',answer:'Treatwell may fit if marketplace customer discovery and broader salon POS/marketing features are important. KERSIVO may fit if most clients find you directly and you value £0 Starter or a £39/month branded Full website with 0% KERSIVO platform commission.'},
{question:'Is KERSIVO an alternative to Treatwell Connect or Treatwell Pro?',answer:'Yes. Treatwell calls its business-side software Treatwell Connect and also refers to Treatwell Pro in some partner materials. KERSIVO is independent barber booking software: Starter has a hosted booking page and Full provides a branded website with direct booking.'},
{question:'What is the 365-day rule in Treatwell’s new-client commission?',answer:'Under Treatwell’s September 2026 Partner Terms, a booking may qualify as new when a customer has not had a successful appointment during the previous 365 days, among other conditions. This means a returning customer can sometimes be treated as new. Actual commission depends on marketplace source and your partner agreement.'},
{question:'What is the difference between Treatwell Freelancer and Advanced?',answer:'Treatwell lists Freelancer and Advanced partner plans. Both promote marketplace discovery and booking tools. Advanced includes unlimited staff members, along with salon reporting, POS and other features shown in the UK pricing comparison. Confirm a venue-specific subscription quotation.'},
{question:'Can I run KERSIVO and Treatwell bookings simultaneously?',answer:'Treatwell’s September 2026 Partner Terms include restrictions on using other third-party software to enable customer bookings. Review your own signed contract before running both booking systems publicly. It is safer to prepare your KERSIVO site and plan the switch before changing live links.'},
];
export function buildTreatwellAlternativeFaqJsonLd(): Record<string,unknown> {
const pageUrl = `${getPublicSiteUrl()}${TREATWELL_ALTERNATIVE_PAGE_PATH}`;
return {'@context':'https://schema.org','@type':'FAQPage','@id':`${pageUrl}#faq`,mainEntity:TREATWELL_ALTERNATIVE_FAQ_ITEMS.map(item=>({'@type':'Question',name:item.question,acceptedAnswer:{'@type':'Answer',text:item.answer}}))};
}