export const TREATWELL_FACTS_CHECKED_ISO = '2026-10-08';
export const TREATWELL_FACTS_CHECKED_DATE = '8 October 2026';
export const TREATWELL_SOURCES = [
 {label:'Treatwell UK partner pricing', url:'https://www.treatwell.co.uk/partners/pricing/',supports:'Published UK new-client marketplace commission, repeat bookings, prepayment fees and salon tools'},
 {label:'Treatwell supplier terms',url:'https://www.treatwell.co.uk/info/supplier-terms-and-conditions/',supports:'Contract terms; confirm individual commission and applicable VAT'},
 {label:'Treatwell Connect information',url:'https://www.treatwell.co.uk/partners/ai-instructions/',supports:'Marketplace and salon management features'},
] as const;
export const TREATWELL_TRADEMARK_DISCLAIMER='Treatwell is a trademark of its respective owner. KERSIVO is not affiliated with, endorsed by or sponsored by Treatwell.';
export const TREATWELL_COMPARISON_FOOTNOTE='Treatwell UK information is based on published partner pricing and terms checked 8 October 2026. Individual agreements and features can differ.';
export const TREATWELL_COMPARE_SECTIONS = [
{id:'bookings',title:'Bookings',subtitle:'Scheduling, staff diaries and booking journeys.',treatwellLead:'Online bookings through marketplace listings and direct channels.',treatwellPoints:['Treatwell marketplace discovery, website and social booking integrations','Appointment calendar, availability, reminders and team management','Suitable for hair and beauty businesses including men’s grooming'],kersivoLead:'Direct-booking system designed for independent UK barbershops.',kersivoPoints:['Starter: hosted booking page for up to four active bookable barbers','Full: branded website on a standard domain and larger barber teams','Email reminders on Starter; SMS reminders on Full']},
{id:'payments',title:'Payments & Deposits',subtitle:'Marketplace commission versus online payment processing.',treatwellLead:'Different charges apply to qualifying marketplace clients and online prepayments.',treatwellPoints:['35% published commission on qualifying first appointments by new marketplace customers','0% marketplace commission for repeat customers and direct website/social bookings','Published online prepayment processing fee of 2.5% + VAT; confirm applicable contract'],kersivoLead:'No KERSIVO booking commission; card processing is separate.',kersivoPoints:['Starter: public bookings require a £5 deposit towards service or pay in full via Stripe','Both plans: 0% KERSIVO booking commission; Stripe processing fees apply','Full: Pay at shop, £5 deposit or full online payment modes']},
{id:'brand',title:'Brand & Domain',subtitle:'Marketplace visibility versus a branded direct-booking site.',treatwellLead:'Marketplace discovery alongside direct booking options.',treatwellPoints:['Treatwell listing gives customers another way to discover your business','Booking widgets and connections with existing websites/social profiles','Marketplace listing is not the same offering as a bespoke branded shop site'],kersivoLead:'One direct path from your shop’s links to your booking journey.',kersivoPoints:['Starter: KERSIVO-hosted booking page','Full: branded website plus one standard domain per location','Use your own public Google, Instagram, website and QR booking links']},
{id:'retail',title:'Retail & Growth Tools',subtitle:'Compare salon POS tools and retail pickup.',treatwellLead:'Broader salon operating features on eligible plans.',treatwellPoints:['POS and product sales capabilities','Marketing, reviews and retention tools','Feature availability depends on plan and contract'],kersivoLead:'Focused retail pickup with Full KERSIVO.',kersivoPoints:['Full: online product orders for in-shop collection','Product/order tools rather than a full POS or stock-management replacement','No KERSIVO retail commission; Stripe payment fees still apply']},
{id:'clients',title:'Clients',subtitle:'Records and repeat appointments.',treatwellLead:'Client records, repeat booking and review tools.',treatwellPoints:['Client database and booking history','Reviews and repeat-visit marketing features','Repeat appointments from Treatwell customers advertised as commission-free'],kersivoLead:'Starter core records and richer Full client tools.',kersivoPoints:['Starter: Clients Core and rolling 90-day booking history','Full: Advanced Clients / CRM and complete booking history','Direct customer booking experience focused on your brand']},
{id:'reports',title:'Reports & Shop Operations',subtitle:'Understand your operational toolkit.',treatwellLead:'Salon software with reporting and POS-related capabilities.',treatwellPoints:['Calendar, team scheduling and business reporting','Marketing and payment features depending on plan','Useful if you want a wider beauty/salon ecosystem and marketplace discovery'],kersivoLead:'Clear barber-focused day-to-day tools.',kersivoPoints:['Starter: booking, team and service management','Full: reports, advanced clients, retail pickup and SMS reminders','Full costs £39/month per shop location, with no per-barber subscription charge subject to fair use']},
] as const;
export type TreatwellCompareSectionId = (typeof TREATWELL_COMPARE_SECTIONS)[number]['id'];