import type { InsightCardItem, ModelComparisonItem } from '@/lib/editorial/insightIcons';

export const VAGARO_FACTS_CHECKED_ISO = '2026-10-08';
export const VAGARO_FACTS_CHECKED_DATE = '8 October 2026';
export const VAGARO_SOURCES = [
  {label:'Vagaro UK pricing',url:'https://www.vagaro.com/en-gb/pro/pricing',supports:'One-calendar UK pricing, bookable-calendar model, marketplace fee headline and included tools'},
  {label:'Vagaro UK Customer Participation Agreement',url:'https://www.vagaro.com/en-gb/pro/vagaro-customer-participation-agreement',supports:'UK-specific channel conditions, 20% new-client connection fee and optional promotions'},
  {label:'Export your customer list — Vagaro Support',url:'https://support.vagaro.com/hc/en-us/articles/360006371094-Export-Your-Customer-List',supports:'Business-owner export to Excel or PDF'},
] as const;

export const VAGARO_COMPARE_SECTIONS = [
{id:'bookings',title:'Bookings',subtitle:'Scheduling, reminders and online booking.',vagaroLead:'A multi-industry appointment platform with marketplace discovery.',vagaroPoints:['Online appointment booking and staff calendars','Booking widget for a business website','Vagaro Marketplace, Instagram and Facebook booking channels','Waitlists and automated appointment reminders'],kersivoLead:'A barber-specific core booking system.',kersivoPoints:['Starter supports up to four bookable barbers','Hosted booking page on Starter; own-domain website on Full','Email reminders on Starter and SMS reminders with Full','Manual bookings and barber availability tools']},
{id:'payments',title:'Pricing & Payments',subtitle:'Monthly pricing, deposits and acquisition fees.',vagaroLead:'Pricing scales with bookable calendars, with channel-dependent acquisition fees.',vagaroPoints:['UK pricing currently displays £20/month promotional price, £30 crossed-out, for one bookable calendar','20% first-appointment new-client fee may apply to qualifying UK marketplace/partner bookings','UK terms contain channel-specific conditions for booking widgets and promoted listings','Payment processing and optional paid services are separate considerations'],kersivoLead:'£0/month Starter or £39/month Full, with 0% KERSIVO commission.',kersivoPoints:['Starter public bookings require £5 online deposit or full payment','Stripe payment-processing fees still apply','Full enables configurable deposits, full payment or Pay at shop','Full pricing is per location, not per barber']},
{id:'brand',title:'Brand & Website',subtitle:'Where your customers book.',vagaroLead:'Vagaro offers its own marketplace plus website booking widgets.',vagaroPoints:['Customers can discover businesses through Vagaro Marketplace','Business and employee booking widgets are available','Booking via social media channels is supported'],kersivoLead:'Make your own barbershop brand the destination.',kersivoPoints:['Starter uses a KERSIVO-hosted booking page','Full includes a branded website and standard domain','No KERSIVO consumer marketplace or acquisition commission','Direct customer booking journey under your own brand on Full']},
{id:'retail',title:'Retail & Operations',subtitle:'Products, sales and other tools.',vagaroLead:'Broad salon, wellness and fitness business management.',vagaroPoints:['Vagaro lists inventory tracking and invoices','Memberships, packages and gift certificates','Loyalty and marketing tools'],kersivoLead:'Focused barbershop operations.',kersivoPoints:['Full includes products and online retail pickup','Retail checkout through the barbershop Stripe account','No full inventory or shipping management is claimed','Full includes booking reports and sales reporting']},
{id:'clients',title:'Clients',subtitle:'Customer history and portability.',vagaroLead:'Customer records with an official export option.',vagaroPoints:['Customer tracking and client data','Owner can export a customer list to Excel or PDF','Marketing and loyalty functionality'],kersivoLead:'Core contacts in Starter, deeper client tools in Full.',kersivoPoints:['Starter Clients Core with rolling 90-day booking history','Full Advanced Clients / CRM and retained booking history','Migration assistance for compatible available exports']},
{id:'reports',title:'Reporting',subtitle:'Understanding your business.',vagaroLead:'Advanced business reporting is listed in Vagaro plans.',vagaroPoints:['Advanced reports and customer tracking','Inventory and appointment management','Additional capabilities across beauty and wellness categories'],kersivoLead:'Operational focus for independent UK barbers.',kersivoPoints:['Starter bookings, team and services','Full booking performance reports','Full product order and retail sales reports']},
] as const;
export type VagaroCompareSectionId = (typeof VAGARO_COMPARE_SECTIONS)[number]['id'];
export const VAGARO_COMPARISON_FOOTNOTE = 'Vagaro UK information checked 8 October 2026. Marketplace and promotions fees depend on booking channel, settings and eligibility. Verify your own terms.';

export const VAGARO_QUICK_ANSWER_KICKER='The short version';
export const VAGARO_QUICK_ANSWER_TITLE='Vagaro vs KERSIVO: the short answer for UK barbers.';
export const VAGARO_QUICK_ANSWER_LEAD='Looking for a Vagaro alternative in the UK? Vagaro is a broader beauty, wellness and fitness booking platform with calendar-based pricing and a consumer marketplace. KERSIVO is built specifically for independent UK barbershops: Starter is £0/month for up to four bookable barbers, while Full is £39/month per location with a branded website and standard domain.';
export const VAGARO_QUICK_ANSWER_DETAIL='Vagaro UK currently shows £20/month for one bookable calendar against a crossed-out £30 price. Vagaro also publishes a 20% new-client connection fee for certain UK booking channels. KERSIVO takes 0% KERSIVO commission, while Stripe processing fees still apply. Vagaro has several features KERSIVO does not claim, including memberships and inventory tracking.';
export const VAGARO_QUICK_ANSWER_FACTS=[{label:'KERSIVO Starter',value:'£0/month · up to 4 barbers'},{label:'Full KERSIVO',value:'£39/month per location'},{label:'Vagaro UK (1 calendar)',value:'£20/month shown · £30 crossed out'},{label:'UK Vagaro marketplace',value:'20% qualifying first appointment'}];
export const VAGARO_WHY_INTRO='Vagaro has a broad feature set. UK barbers usually need to compare the booking channels, price per calendar, customer acquisition rules and the degree of control over their own brand.';
export const VAGARO_WHY_THEMES: readonly InsightCardItem[]=[
{icon:'seats',title:'Pricing per bookable calendar',body:'Vagaro pricing is organised around bookable calendars. KERSIVO Full is priced per barbershop location rather than per individual barber; Starter allows up to four active bookable barbers.'},
{icon:'discovery',title:'Marketplace or direct booking',body:'Vagaro offers marketplace discovery and UK-specific new-client fee rules. KERSIVO focuses on direct barbershop bookings without a KERSIVO acquisition commission.'},
{icon:'storefront',title:'Own-domain customer experience',body:'Vagaro provides booking widgets for existing sites. Full KERSIVO includes the barbershop website and standard domain together with booking and retail pickup.'},
{icon:'stack',title:'Breadth versus barber focus',body:'Vagaro lists memberships, gift certificates and inventory tools. KERSIVO concentrates on core barber operations, with Full CRM, reporting and retail pickup.'},
];
export const VAGARO_FIT_PATHS: readonly [ModelComparisonItem,ModelComparisonItem]=[
{label:'Vagaro',descriptor:'Multi-industry software with marketplace discovery',icon:'network',summary:[{label:'Pricing',value:'Calendar-based subscription'},{label:'Acquisition',value:'Marketplace and promoted bookings'}],heading:'Vagaro may suit your shop if…',points:['Marketplace discovery is important to your acquisition strategy','You want memberships, gift certificates or inventory management','Your shop already uses the broader Vagaro ecosystem','You prefer booking widgets on an existing website']},
{label:'KERSIVO',descriptor:'Booking software built around independent barbers',icon:'direct',summary:[{label:'Pricing',value:'£0 Starter / £39 Full'},{label:'Commission',value:'0% KERSIVO fee'}],heading:'KERSIVO may suit your shop if…',points:['You want a £0/month core booking plan for up to four barbers','You want Full bookings centred on your own branded website and standard domain','You prefer 0% KERSIVO commission with normal Stripe fees separate','You want Full retail pickup, CRM and barber-focused reports']},
];
export const VAGARO_FIT_CLOSING='Choose Vagaro for its broader marketplace and business-tool ecosystem, or KERSIVO for a barber-first direct-booking model. Verify all applicable fees before deciding.';
export const VAGARO_SWITCHING_REASSURANCE='Keep Vagaro running while your KERSIVO setup is prepared.';
export const VAGARO_SWITCHING_STEPS=[
{title:'Keep Vagaro bookings live',body:'Do not interrupt your existing diary while you review alternatives.'},
{title:'Export your client list',body:'Vagaro says business owners can export their customer list to Excel or PDF from Reports → Customers.'},
{title:'Review the usable records',body:'KERSIVO can assess compatible data and supported CSV exports. Excel data may need conversion or mapping; not all fields are transferable.'},
{title:'Configure barbers, services and hours',body:'Set up the booking experience in KERSIVO while the old system remains accessible.'},
{title:'Check the Full site preview',body:'For Full KERSIVO, approve the private branded website preview before launch.'},
{title:'Switch booking links when ready',body:'Update customer-facing booking links after confirming the transition plan and future bookings.'},
];
export const VAGARO_SWITCHING_LIMITS=['Vagaro documents customer-list export to Excel/PDF, not a guaranteed all-data migration format.','Future appointments, reviews and every historical record are not guaranteed to transfer. Confirm available exports and preserve access to existing bookings.'];
