/** Runtime-safe list of pair rejection codes for Zod validation. */
export const PAIR_REJECTION_CODES = [
  'SERVICE_PROFILE_LOW_CONFIDENCE',
  'PRODUCT_PROFILE_LOW_CONFIDENCE',
  'SERVICE_CRITICAL_FIELD_LOW_CONFIDENCE',
  'PRODUCT_CRITICAL_FIELD_LOW_CONFIDENCE',
  'SERVICE_RETAIL_NEEDS_UNKNOWN',
  'PRODUCT_RETAIL_NEEDS_UNKNOWN',
  'NO_RETAIL_NEED_OVERLAP',
  'NO_TARGET_AREA_OVERLAP',
  'HAIR_LENGTH_MISMATCH',
  'BEARD_ONLY_PRODUCT',
  'HAIR_ONLY_PRODUCT',
  'POST_SHAVE_ONLY_PRODUCT',
  'NOT_FOR_BEARD',
  'NOT_FOR_SHAVE',
  'MATCH_SCORE_BELOW_THRESHOLD',
] as const;

export type PairRejectionCodeLiteral = (typeof PAIR_REJECTION_CODES)[number];
