import { FPS, HEIGHT, WIDTH } from './theme';

export { FPS, WIDTH, HEIGHT };

export const SPINNING_CHAIR_DURATION_SECONDS = 3;
export const SPINNING_CHAIR_DURATION_FRAMES = FPS * SPINNING_CHAIR_DURATION_SECONDS;
