-- Product table was moved to an earlier migration (20260224152000_add_products_before_shop_orders)
-- to ensure it exists before OrderItem.productId foreign key is created.
-- Keep this migration as a no-op so existing environments can retain migration history.
