/**
 * Feature → KPI coaching for every major admin control.
 * Dense bullets — injected into the system prompt with the navigation playbook.
 */
export const ADMIN_RESULTS_PLAYBOOK = {
  id: 'admin-results',
  title: 'Admin feature → results coaching',
  body: [
    '## KPI dictionary (use consistently)',
    '- Utilisation: booked chair minutes ÷ available minutes (Reports). Strong shops protect this daily.',
    '- No-show rate / no-show £: empty chairs from missed appointments (Reports + Bookings discipline).',
    '- Cancelled rate: client vs shop vs no-show breakdown — honesty in status marks makes Reports trustworthy.',
    '- AOV (avg booking / order value): ticket size on services or retail.',
    '- Retail attach: products sold / collected alongside or after services.',
    '- Reliability: client score from completed vs no-shows — drives deposits, reminders, VIP treatment.',
    '- Peak day/hour + busiest barber: where demand concentrates — staff and hours should follow.',
    '',
    'Answer habit for feature questions: Where → How → Results (KPI + one weekly habit). Offer one primary lever and one follow-up tab.',
    '',
    '## Bookings — run the floor for utilisation',
    '- Timeline: use to see gaps and double-books visually. Habit: open each morning; fill obvious gaps with walk-ins or same-day slots. Drives utilisation.',
    '- List + search (Ctrl/⌘K): find a client/booking fast when the floor is busy. Habit: act within minutes on late arrivals. Protects no-show £.',
    '- Still to come filter: prioritise who is next; chase lateness early. Cuts dead chairs before they become no-shows.',
    '- Rescheduled filter: confirm the new slot is real and the old gap is fillable. Protects utilisation after moves.',
    '- Cancelled filter: spot patterns (same day, same barber). Follow up in History/Clients. Improves cancelled-rate honesty.',
    '- On shift / Staff: only count chairs that are actually available. Ghost “on shift” kills utilisation math.',
    '- No Show: mark promptly when the client does not arrive. Clean data → Reports no-show KPI; then tag the client for deposits.',
    '- Cancel by shop: use when the shop cannot deliver — not as a soft no-show. Keeps cancelled-rate breakdown honest.',
    '- Reschedule: prefer moving over losing the booking; then fill the freed slot. Net utilisation up.',
    '- Change service: upsell/correct duration before the cut starts. Lifts AOV and stops overruns that block the next booking.',
    '- Client panel from a booking: read notes/tags before they sit down; add a note after. Better service + retail attach.',
    '',
    '## Barbers — match supply to demand',
    '- Active roster: only Active barbers should appear bookable. Inactive ghosts inflate supply and tank utilisation.',
    '- Service assignment: every popular service needs enough barbers. Gaps here force “unavailable” and lost AOV.',
    '- Working hours On/Off + start–end: align to peak day/hour from Reports. Off-shift on dead mornings; cover Saturday peaks.',
    '- Break TIME OFF: short blocks for lunch — prevents mid-day overbooking and walk-in chaos.',
    '- Vacation TIME OFF: multi-day blocks so clients cannot book empty chairs. Protects trust and no-show/cancel noise.',
    '- Deactivate vs delete: deactivate leavers to keep History/Reports clean; delete only true mistakes. Preserves pattern analysis.',
    '- Roster reorder: put strongest peak barbers where the team sees them first for ops decisions.',
    '',
    '## Reports — weekly ops rhythm',
    '- Range (7/30/90 + custom): run a weekly 7-day check and a monthly 30-day review. Trends vs prior period beat gut feel.',
    '- Utilisation low: tighten hours (Barbers), cut ghost availability, fill gaps from Bookings Timeline, shorten dead services.',
    '- Cancelled rate high — Client cancel: deposits + reminders; tag risk clients. Shop cancel: staffing/TIME OFF discipline.',
    '- No-show high: deposits on peak slots; Bookings No Show hygiene; Clients reliability tags; SMS reminders.',
    '- AOV low: Services price/duration mix, Change service upsells, Featured services, retail attach after cuts.',
    '- Peak day/hour: staff those windows; push online booking into quieter slots with offers if needed.',
    '- Most popular service: ensure barber assignment + Featured; keep duration realistic so the next slot stays bookable.',
    '- Busiest barber / leaderboard: balance load (hours/services) or celebrate and clone their service mix. Open profile from the row.',
    '- Small sample (<~10 bookings): do not overreact — wait for more data.',
    '',
    '## History — investigate patterns, then act',
    '- Barber chips + date range + search: find repeat no-shows, shop cancels, or one barber’s chaos week.',
    '- Habit: after a bad Reports week, pull History for that barber/range → tag Clients → fix Barbers hours or TIME OFF.',
    '- Open client from a row: convert a pattern into a note/tag/deposit rule. Improves reliability over time.',
    '- Do not use History as the live day board — that is Bookings.',
    '',
    '## Clients — turn CRM into revenue protection',
    '- Search (name/email/phone): find risk or VIP clients in seconds before they book peak slots.',
    '- Reliability score: low → require deposit / reminder discipline; high → priority slots and softer policies.',
    '- Tags: e.g. no-show-risk, VIP, retail-buyer. Make filters and memory consistent across the team.',
    '- Notes (+ images): capture preferences and product interest → higher retail attach next visit.',
    '- Message client: win-back quiet regulars (last visit old, spend high). Recovers utilisation and AOV.',
    '- Stats (completed, no-shows, spend, favourite service): personalise offers; push favourite + aftercare product.',
    '- Avatar/photo: faster recognition on the floor → better hospitality and less wrong-chair chaos.',
    '',
    '## Services — price the chair correctly',
    '- Price £ + duration minutes: AOV and utilisation are a pair — too long blocks the next booking; too cheap leaves money on the table.',
    '- Barber assignment: popular services on enough chairs. Bottlenecks show up as empty demand, not empty chairs.',
    '- Featured / category: surface high-margin or hero cuts first on the booking site. Improves mix and AOV.',
    '- Active/Inactive: retire dead services instead of leaving zombie options that confuse clients.',
    '- Reorder (Manual): put best sellers and profitable add-ons where clients see them first.',
    '- Habit: monthly pass — align top 3 services with Reports “most popular” and leaderboard capacity.',
    '',
    '## Products — retail attach at the till',
    '- Active catalogue: only sell what is on the shelf. Ghost products destroy trust and Orders noise.',
    '- Featured + image: highlight aftercare that pairs with fades/beards. Attach rate after the cut.',
    '- Reorder / bulk activate: keep bestsellers first; seasonal push without clutter.',
    '- Habit: after each Completed booking, offer one Featured product — track via Sales AOV/units.',
    '',
    '## Orders — fulfilment discipline',
    '- Paid → Mark as Collected: same-day habit when the customer picks up. Cuts “lost” pickups and angry returns.',
    '- Search + expand row: confirm items before handing over. Protects trust and Sales accuracy.',
    '- Open client: note retail buyers for next-visit attach.',
    '- Badges paid vs collected: end-of-day zero unpaid-collected backlog. Cleaner Sales KPIs.',
    '',
    '## Sales — steer what you feature and push',
    '- Revenue £ vs Units: revenue for margin focus; units for velocity / attach volume.',
    '- Orders + AOV + Top product: weekly — if AOV flat, push Featured bundles; if units down, fix Products Active/images.',
    '- Product leaderboard: double-down Featured on winners; deactivate or reprice dogs.',
    '- Habit: after Reports booking review, open Sales 7 days — connect chair traffic to retail attach.',
    '',
    '## Cross-tab weekly play (strong shops)',
    '1. Reports 7d: utilisation, no-show, AOV.',
    '2. Bookings: mark statuses honestly all week.',
    '3. Barbers: hours/TIME OFF match peaks.',
    '4. Clients: tag new no-show risks; message 5 quiet VIPs.',
    '5. Services/Products: Featured list matches what actually sells.',
    '6. Orders: zero stale Paid not Collected.',
    '7. Sales: confirm retail moved with traffic.',
  ].join('\n'),
} as const;
