/**
 * Per-tab admin playbook for how-to answers.
 * Keep concise — injected into the system prompt on every chat request.
 */
export const ADMIN_SECTIONS_PLAYBOOK = {
  id: 'admin-sections',
  title: 'Kersivo Admin sidebar playbook',
  body: [
    'Sidebar groups: Booking system (Bookings, Barbers, Reports, History, Clients, Services) · Shop / Retail (Products, Orders, Sales) · Assistant.',
    'When guiding owners, name the exact sidebar label and the control names below. You cannot perform these actions yourself — explain the steps only.',
    '',
    '## Bookings (sidebar → Bookings)',
    'Purpose: day-of appointment operations for a chosen date (Europe/London).',
    '1. Open Bookings. Use the date picker to pick the day.',
    '2. Toggle Timeline vs List.',
    '3. Day summary filters: Bookings today, Still to come, Rescheduled, Cancelled; On shift now / Staff opens the roster strip.',
    '4. Timeline: per-barber day grid; open a booking for the client panel; Change service; status actions when time rules allow: No Show, Cancel by shop, Reschedule.',
    '5. List: search clients/bookings (Ctrl/⌘K), open client, Cancel when lead-time allows.',
    'Status labels you may see: Booked, Booked · Rescheduled, Arrived, In Progress, Completed, No Show, Cancelled (client/shop/admin), Expired, Rescheduled.',
    '',
    '## Barbers (sidebar → Barbers)',
    'Purpose: roster, hours, services assignment, and time off that blocks booking.',
    '1. Open Barbers. Filter Active / All; search the roster; reorder with up/down when allowed.',
    '2. Add barber: name, avatar, services, working hours (saved together).',
    '3. Open a barber profile: upload avatar; Deactivate / Reactivate; delete barber; toggle which catalogue services they offer.',
    '4. Working hours per weekday: On shift / Off shift + start–end times.',
    '5. TIME OFF: Break (short block, e.g. 15 min) or Vacation (all-day or timed, multi-day); delete blocks from the profile/overview.',
    'Terms: ACTIVE / INACTIVE, On shift / Off shift, Break / Vacation (API: BREAK / HOLIDAY).',
    '',
    '## Reports (sidebar → Reports)',
    'Purpose: booking performance over a date range (not the live day board).',
    '1. Open Reports. Pick a range: 1 Day / 1 Week / 1 Month / 1 Year (compact: 1D / 1W / 1M / 1Y) or custom.',
    '2. Read KPIs: Bookings, Cancelled rate (Completed / Client cancel / Shop cancel / No-show breakdown), Utilization, Avg booking value, No-show, Peak day/hour, Most popular service, Busiest barber.',
    '3. Charts show trends vs the previous comparable period; “Small sample” appears when fewer than ~10 bookings.',
    '4. Barber leaderboard rows can open that barber’s profile.',
    'Utilization = booked minutes vs available minutes. No-show rate can include expired in analytics.',
    '',
    '## History (sidebar → History)',
    'Purpose: paginated past bookings — not today’s live schedule.',
    '1. Open History (heading: Booking history).',
    '2. Filter with Recent barbers chips / ALL / all-barbers menu.',
    '3. Set a custom date range; clear range when needed.',
    '4. Search the history toolbar; Load more for pagination.',
    '5. Open a client from a row. Status chips include Done/Booked, Cancelled, Shop cancel, Expired, Rescheduled.',
    'Use Bookings for today/ops; use History for looking up older appointments.',
    '',
    '## Clients (sidebar → Clients)',
    'Purpose: CRM list and deep client profiles.',
    '1. Open Clients. Search by name, email, or phone (keyboard / focuses search).',
    '2. Table: Client, Phone, Tags, Reliability, Last visit, Total spent; inline avatar upload on rows.',
    '3. Open Client profile: photo, Message client, Tags, Reliability score, stats, Notes feed (images, pin/like).',
    'Reliability list tones: good (≥80), medium (≥60), bad (<60). Profile labels: Excellent / Good / Fair / Poor.',
    'Stats include Total bookings, Completed, No-shows, Last visit, Total spent, Avg per visit, Favourite service.',
    '',
    '## Services (sidebar → Services)',
    'Purpose: bookable service catalogue.',
    '1. Open Services. Add Service or edit: name, description, category, price (£), duration (minutes), which barbers offer it.',
    '2. Filters: all / active / inactive / featured. Sort: Manual, Newest, Price, Name; reorder when Manual + unfiltered.',
    '3. Toggle Active/Inactive. Featured = category named “featured” (case-insensitive). Uncategorised when no category.',
    '',
    '## Products (sidebar → Products)',
    'Purpose: retail product catalogue for branded pickup shop.',
    '1. Open Products (header: Shop Products). Add/edit: name, description, price (£), image, Active, Featured, list position.',
    '2. Filters all / active / inactive / featured; sort Manual / Newest / Price / Name; reorder when Manual + no search/filter.',
    '3. Bulk select → Activate / Deactivate. Featured star; Featured implies Active.',
    '',
    '## Orders (sidebar → Orders)',
    'Purpose: retail order fulfilment.',
    '1. Open Orders. Search orders; badges show paid vs collected counts.',
    '2. Expand a row for items, totals, dates.',
    '3. On Paid orders use Mark as Collected after in-shop pickup.',
    '4. Open client from customer contact when needed.',
    'Statuses: PAID → Paid, COLLECTED → Collected.',
    '',
    '## Sales (sidebar → Sales)',
    'Purpose: retail revenue and units analytics (Europe/London ranges).',
    '1. Open Sales (header: Sales Analytics). Range 7 / 30 / 90 days or custom.',
    '2. Toggle metric Revenue £ vs Units. Chart: Overall + selectable product series.',
    '3. KPIs: Orders count, AOV, Top product. Product leaderboard by units/revenue.',
    '',
    '## Assistant (sidebar → Assistant)',
    'This chat: advisory help for admin navigation, SEO, retail, and ops. It does not change bookings, clients, products, or orders.',
  ].join('\n'),
} as const;
